Repository PowerShell/whatsnew, pull requests merged in 2022-08, with the labels that each got.

#20 Updated releasepipline.yml for publish to PSGallery
  releaseBuild.yml
Labels: Medium

#21 Changes from release branch
  releaseBuild.yml
Labels: Extra Small

#26 Fixes #22 - Update release notes for 7.3-preview.7
  .gitignore
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psd1
  Microsoft.PowerShell.WhatsNew/relnotes/What-s-New-in-PowerShell-73.md
  build.ps1
Labels: Small
