Repository PowerShell/whatsnew, pull requests merged in 2022-06, with the labels that each got.

#2 Code clean up and docs refresh
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psd1
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psm1
  Microsoft.PowerShell.WhatsNew/relnotes/What-s-New-in-PowerShell-73.md
Labels: Large

#3 Support ValidateScript rather than ValidateSet.
  .gitignore
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psd1
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psm1
  build.ps1
Labels: Small

#5 Simplify parameter sets
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psm1
  Microsoft.PowerShell.WhatsNew/relnotes/What-s-New-in-PowerShell-Core-60.md
  Microsoft.PowerShell.WhatsNew/relnotes/What-s-New-in-PowerShell-Core-61.md
  Microsoft.PowerShell.WhatsNew/relnotes/What-s-New-in-PowerShell-Core-62.md
  Microsoft.PowerShell.WhatsNew/relnotes/What-s-New-in-Windows-PowerShell-50.md
Labels: Extra Large

#6 Add spec and questions
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psm1
  spec/Get-WhatsNew.specification.md
  spec/questions.md
Labels: Medium

#7 Fix handling version numbers in an array
  Microsoft.PowerShell.WhatsNew/Microsoft.PowerShell.WhatsNew.psm1
  build.ps1
  test/WhatsNew.Tests.ps1
Labels: Extra Small
